title: CS167 Machine Learning
email: timothy.urness@drake.edu
description: "Course materials and notes for Drake University's CS167: Machine Learning"
baseurl: ""
url: "https://drakecs167spring22.github.io/"

theme: jekyll-theme-minimal
